# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    # Debricked adapter implementation: 'curl' or 'guzzle'
    # Switch to 'guzzle' when ready to use the new Guzzle-based implementation
    debricked.adapter.type: 'guzzle'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Message/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Scan Service
    App\Contract\Service\ScanServiceInterface:
        alias: App\Service\ScanService

    App\Service\ScanService:
        arguments:
            $filesystem: '@s3.storage'

    # Message Handler
    App\MessageHandler\StartProviderScanHandler:
        arguments:
            $filesystem: '@s3.storage'

    # Repository Service
    App\Contract\Service\RepositoryServiceInterface:
        alias: App\Service\RepositoryService

    App\Service\RepositoryService:
        arguments:
            $em: '@doctrine.orm.entity_manager'

    # AWS S3 Client for Flysystem
    aws_s3_client:
        class: Aws\S3\S3Client
        factory: ['Aws\S3\S3Client', 'factory']
        arguments:
            -
                version: 'latest'
                region: '%env(AWS_DEFAULT_REGION)%'
                endpoint: '%env(AWS_ENDPOINT)%'
                use_path_style_endpoint: true
                credentials:
                    key: '%env(AWS_ACCESS_KEY_ID)%'
                    secret: '%env(AWS_SECRET_ACCESS_KEY)%'
     # -------- Provider adapters (tagged) ----------
    # Guzzle HTTP Client for Debricked Provider (testable alternative)
    App\Service\Provider\GuzzleClientForDebricked:
        class: GuzzleHttp\Client
        arguments:
            -
                timeout: 30
                connect_timeout: 10

    # Debricked Provider Adapter - cURL implementation (current/legacy)
    App\Service\Provider\DebrickedProviderAdapter:
        arguments:
            $http: '@http_client'
            $mapping: '@App\Service\ExternalMappingService'
            $logger: '@logger'
            $auth: '@App\Service\Provider\DebrickedAuthService'
            $baseUrl: '%env(DEBRICKED_API_BASE)%'
        # Only register if using curl implementation
        tags:
            - { name: 'app.provider.adapter', when: "%debricked.adapter.type% == 'curl'" }

    # Debricked Provider Adapter - Guzzle implementation (new/testable)
    App\Service\Provider\DebrickedProviderAdapterGuzzle:
        arguments:
            $httpClient: '@App\Service\Provider\GuzzleClientForDebricked'
            $mapping: '@App\Service\ExternalMappingService'
            $logger: '@logger'
            $auth: '@App\Service\Provider\DebrickedAuthService'
            $baseUrl: '%env(DEBRICKED_API_BASE)%'
        # Only register if using guzzle implementation
        tags:
            - { name: 'app.provider.adapter', when: "%debricked.adapter.type% == 'guzzle'" }

    # If you have other provider adapters add them with same tag:
    # App\Service\Provider\SnykProviderAdapter:
    #   tags: ['app.provider.adapter']

    # -------- ProviderManager: use tagged_iterator ----------
    App\Service\Provider\ProviderManager:
        arguments:
            $adapters: !tagged_iterator 'app.provider.adapter'
            $logger: '@logger'

    # ExternalMappingService (DBAL)
    App\Service\ExternalMappingService:
        arguments:
            $conn: '@doctrine.dbal.default_connection'

    # Debricked Auth Service
    App\Service\Provider\DebrickedAuthService:
        arguments:
            $http: '@http_client'
            $username: '%env(DEBRICKED_USERNAME)%'
            $password: '%env(DEBRICKED_PASSWORD)%'
            $refreshToken: '%env(DEBRICKED_REFRESH_TOKEN)%'
            $baseUrl: '%env(DEBRICKED_API_BASE)%'
            $logger: '@logger'

